version: '3.3'

services:
  nginx:
    image: 400206/simplezat-nginx:stable
    ports:
      - "8000:80"
    volumes:
      - app-staticfiles:/app/static

  db:
    image: postgres:11.1-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: 400206/simplezat:stable
    volumes:
      - app-staticfiles:/app/static
    command: ./entrypoint.dev.sh

volumes:
  postgress-data:
  app-staticfiles:
