version: '3.3'

services:
  app:
    image: 400206/simplezat:unstable
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ./entrypoint.sh