FROM python:3.7.1-alpine

MAINTAINER 400206

ENV APPLICATION_ROOT /app
RUN mkdir $APPLICATION_ROOT
WORKDIR $APPLICATION_ROOT

Run pip3 install pipenv


COPY . $APPLICATION_ROOT/
Run pipenv install --dev --ignore-pipfile

EXPOSE 8000