version: '3.3'

services:
  db:
    image: postgres:11.1
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: 400206/simplezat:unstable
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ./entrypoint.sh

volumes:
  postgres-data: